WatchTower-Technology
Markson17/MLSA-GitHub-Practice pull request #6
Opened 2024-06-08 21:48 UTC by WatchTower-Technology

2024-06-08 21:53 UTC, Qudusayo requested changes
You should fix that

2024-06-08 21:53 UTC, Qudusayo commented on README.md
> -</p>
This PR is removing this user data, rather you should sync update with your forked version before making a PR

2024-06-09 07:42 UTC, WatchTower-Technology commented
I don’t still understand

On Sat, Jun 8, 2024 at 10:54 PM, Ayoola Abdulqudus ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> You should fix that
> ------------------------------
>
> In README.md
> <https://github.com/Markson17/MLSA-GitHub-Practice/pull/6#discussion_r1632118307>
> :
>
> > -
> -<p style="display: flex; align-items:center; gap:10px;">
> -  <img src="https://github.com/SulaimonShittu.png" width="40px" height="40px" style="border-radius:50%"  />
> -  <a href="https://github.com/SulaimonShittu">Sulaimon Shittu</a>
> -</p>
>
> This PR is removing this user data, rather you should sync update with
> your forked version before making a PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Markson17/MLSA-GitHub-Practice/pull/6#pullrequestreview-2105986360>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BH2KSSWHTOW3DN6KJQS2OUDZGN4QBAVCNFSM6AAAAABJAJR2NKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMBVHE4DMMZWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-09 16:21 UTC, Markson17 commented
I would advice you delete this pull request and the fork, re fork the repo then add yourself as a participant again in your branch

2024-06-10 18:32 UTC, merged